#' data simulator
#'
#' @description
#' This function generate binary data sets for simulation study
#'
#' @param N number of samples
#' @param P number of predictors
#' @param p_ref number of relevant predictors
#' @param tau bias
#' @param sigma variance
#' @param rho correlation
#' @param link link function
#'
#' @returns list of y and x
#' @export

binary_data_generator <- function(N, P, p_ref, tau, sigma, rho, link = "logit"){

    linkinv <- make.link(link)$linkinv

    f <- rnorm(N, 0, 1)
    y <- rbinom(N, 1, linkinv(tau + sigma*f))

    # regenerate if total number of minor group smaller than 4
    while(sum(y) < 4){
        y <- rbinom(N, 1, linkinv(tau + sigma*f))
    }

    x <- cbind(sqrt(1 - rho) * matrix(rnorm(N*p_ref, 0, 1), nrow = N) +
                   sqrt(rho) * matrix(rep(f, p_ref), nrow = N),
               matrix(rnorm(N * (P - p_ref), 0, 1), nrow = N))

    return(list(y = y, x = x))
}

#' Generate data for simulation study
#'
#' @description
#' Generate data sets using binary_data_generator with default parameter N=50, P=500,
#' p_ref=10, tau=-9, sigma=10, rho=runif(10, 0.05, 0.95) to reflect the unbalanced class
#' proportion
#'
#' @param n no. of simulation data sets
#' @param seed seed for reproducibilty
#'
#' @returns list of data
#' @export

get_simulated_data <- function(
        n = 1,
        N = 50,
        P = 500,
        p_ref = 10,
        tau = -9,
        sigma = 10,
        rho = NULL,
        seed) {

    set.seed(seed)

    if (is.null(rho)) {
        rho <- runif(10, 0.05, 0.95)
    }

    CJ(
        i = 1:n,
        N = N,
        P = P,
        p_ref = p_ref,
        tau = tau,
        sigma = sigma,
        rho = list(rho),
        sorted = FALSE
        ) |>
        pmap(
            function(i, N, P, p_ref, tau, sigma, rho) {
                binary_data_generator(N, P, p_ref, tau, sigma, rho) |>
                    as.data.table() |>
                    _[, y := as.factor(y)] |>
                    setnames(old = paste0("x.V", 1:P), new = paste0("X", 1:P))
                }
        )
}

#' get cross-validation data for simulation study
#'
#' @description
#' The function split the data into training and test data using stratified sampling.
#' The training data is standardised according to the mean and sd of the training data.
#'
#' @param data list of data sets
#' @param seed seed for reproducibility
#'
#' @returns list of data sets
#' @export

get_stratified_cv_data <- function(data, seed) {

    set.seed(seed)

    cv_ind <- map(data, function(x) createDataPartition(x$y, p = 0.7, list = FALSE))

    ## standardise the training and test data ####
    vars <- paste0("X", 1:500)

    simulated_data_rescaled <- map2(
        cv_ind,
        data,
        function(x, y){
            dat <- copy(y)[, c(vars):=lapply(.SD, function(a) (a - mean(a[x]))/sd(a[x])), .SDcols=c(vars)]
            return(list(train = dat[x], test = dat[-x]))
        }
    )

    return(simulated_data_rescaled)
}

#' get cross-validation training data
#'
#' @description
#' The function extract the training data from the list of data sets
#' generated by get_stratified_cv_data.
#'
#'
#' @param data list of data sets
#'
#' @returns list of data sets
#' @export

get_train_cv_data <- function(data) {
    map(data, function(x) x$train)
}

#' get cross-validation test data
#'
#' @description
#' The function extract the test data from the list of data sets
#' generated by get_stratified_cv_data.
#'
#' @param data list of data sets
#'
#' @returns list of data sets
#' @export

get_test_cv_data <- function(data) {
    map(data, function(x) x$test)
}
